Repository cse110-fa21-group21/cse110-fa21-group21, pull requests merged in 2021-12, with the labels that each got.

#69 Ingredients now search with substring
  source/assets/scripts/filter.js
Labels: bug

#80 Add header for instructions and ingredients. Change style for a few components
  source/assets/components/recipeCard/recipeCard.css
  source/assets/components/recipeViewer/recipeViewer.css
  source/assets/components/recipeViewer/recipeViewer.js
  source/styles/main.css
Labels: style

#92 E2E Test for Fav List
  source/assets/_tests_/e2e.test.js
  source/assets/_tests_/main.e2e.test.js
Labels: cicd

#102 JSDoc Config Update
  docs/Router.html
  docs/Router.js.html
  docs/filter.js.html
  docs/global.html
  docs/index.html
  docs/main.js.html
  docs/spoonacular.js.html
  docs/testspoonacular.js.html
  package.json
Labels: documentation

#108 Bug Fixes-Shopping List
  source/assets/scripts/binds/bindFavoriteList.js
  source/assets/scripts/binds/bindRecipeCard.js
  source/assets/scripts/main.js
Labels: bug

#112 Style for Filter List & Recipe Viewer
  source/assets/components/featuredCard/featuredCard.js
  source/assets/components/recipeCard/recipeCard.css
  source/assets/components/recipeViewer/recipeViewer.css
  source/assets/components/recipeViewer/recipeViewer.js
  source/index.html
  source/styles/main.css
  specs/components/recipeViewer/recipeViewer.css
  specs/components/recipeViewer/recipeViewer.html
Labels: style

#120 Responsive Design for the Home Page
  source/assets/components/featuredCard/featuredCard.css
  source/assets/components/featuredCard/featuredCard.js
  source/assets/scripts/main.js
  source/index.html
  source/styles/main.css
Labels: mobile

#119 Shopping List Improvement
  source/assets/components/personalShoppingCard/personalShoppingCard.js
  source/assets/components/recipeViewer/recipeViewer.css
  source/assets/components/recipeViewer/recipeViewer.js
  source/assets/components/shoppingCard/shoppingCard.js
  source/assets/icons/select-all-icon.png
  source/assets/scripts/main.js
Labels: enhancement

#128 filter not show in mobile
  source/assets/scripts/binds/bindRecipeCard.js
Labels: style, mobile
